module BeADragon
  class MotivateMePls
    def self.random_sentence(name)
      sentences = [
        "Friendly reminder: You are the best.",
        "I didn’t fail the test. I just found 100 ways to do it wrong.",
        "Help me rubocup, you are my only hope",
        "I am so clever that sometimes I don’t understand a single word of what I am saying.",
        "You can’t have everything. Where would you put it?",
        "By working faithfully eight hours a day you may eventually get to be boss and work twelve hours a day.",
        "The road to success is dotted with many tempting parking spaces.",
        "Age is of no importance unless you’re a cheese.",
        "It was a fucking semicolon!",
        "Please... close that if statement",
        "No, arrays start at 0, not 1",
        "0101101100010111011001 = you rock!",
        "When tempted to fight fire with fire, remember that the Fire Department usually uses water.",
        "The question isn’t who is going to let me, it’s who is going to stop me.",
        "Work until your bank account looks like a phone number.",
        "If you think you are too small to make a difference, try sleeping with a mosquito.",
        "Bad decisions make good stories.",
        "I’ll probably never fully become what I wanted to be when I grew up, but that’s probably because I wanted to be a ninja princess.",
        "When life gives you lemons, squirt someone in the eye.",
        "A clear conscience is a sure sign of a bad memory.",
        "I used to think I was indecisive, but now I’m not so sure.",
        "Don’t worry about the world coming to an end today. It’s already tomorrow in Australia.",
        "Think like a proton. Always positive.",
        "Leadership is the art of getting someone else to do something you want done because he wants to do it.",
        "Be happy – it drives people crazy.",
        "Even a stopped clock is right twice every day. After some years, it can boast of a long series of successes.",
        "Optimist: someone who figures that taking a step backward after taking a step forward is not a disaster, it’s more like a cha-cha.",
        "You’re only given a little spark of madness. You mustn’t lose it.",
        "A diamond is merely a lump of coal that did well under pressure.",
        "Nothing is impossible, the word itself says “I’m possible!",
        "If you let your head get too big, it’ll break your neck.",
        "Trying is the first step toward failure.",
        "Happiness is just sadness that hasn’t happened yet.",
        "The best things in life are actually really expensive.",
        "A few harmless flakes working together can unleash an avalanche of destruction.",
        "Dreams are like rainbows. Only idiots chase them.",
        "It could be that your purpose in life is to serve as a warning to others.",
        "The light at the end of the tunnel has been turned off due to budget cuts.",
        "Always remember that you are unique – just like everybody else.",
        "That shit ain't gona do itself",
        "Chuck Norris learned programming from you",
        "You can do it! Well, seeing this above, I'm not sure now.",
        "I eat requirements for breakfast",
        "Do it, don't try It, do it or don't do it",
        "Code I must",
        "The programming force is strong on you",
        "May the code be with you",
        "BAAAAAAAARRGWGGH - Chewbacca",
        "Codifilus totalus!",
        "You better go for a coffe",
        "JUST DO-O IT!!",
        "Inhale, exhale, repeat."
        "You should get fired for that #{name}...",
        "You must be kidding, #{name}",
        "Really, #{name}? Really?",
        "Oh come on, put my fingers in my eyes, please, #{name}",
        "#{name}, on the search of the lost semicolon"
      ]
      sentences.sample
    end
  end
end